### ISSUE TITLE
Names are in camelCase

### ISSUE THREAD

**Issue by PurpleMyst** [PurpleMyst/sansio-lsp-client#25]
As per the  title, all of the fields on our models are in camelCase, while python convention is snake_case. Furthermore, we've practically got mixed snake_case and camelCase as method names and arguments are snake_case while actual models are in camelCase.

Should we utilize `pydantic`'s alias feature to make the fields be serialized/deserialized as camelCase but be accessed in code as snake_case?

**Comment by Akuli** [comment]
I think this is a case of "practicality beats purity", and camelCase should stay. It's easy to search for the camelCase names in langserver documentation, and sansio-lsp-client code is simpler without conversions.

**Comment by PurpleMyst** [comment]
That's valid. What should we do about methods and their arguments?

**Comment by Akuli** [comment]
I think they are quite good as they are:
- If a name (method, argument, attribute, whatever) is camelCase, then it's exactly as in langserver documentation.
- If a name is snake_case, then langserver documentation is the wrong place to figure out what it does.

**Comment by PurpleMyst** [comment]
Ah, that's a good way to look at it. I'll close this then.
