### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by Akuli** [PurpleMyst/sansio-lsp-client#53]
```
  /usr/local/lib/python3.11/site-packages/sansio_lsp_client/io_handler.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
```

We use `cgi` for:

```
content_type, metadata = cgi.parse_header(headers["content-type"])
```

**Comment by Moosems** [comment]
Any simple alternatives?

**Comment by Moosems** [comment]
PEP 584 states:

"Replacements for the various parts of cgi which are not directly related to executing code are:

...
parse_header with email.message.Message (see example below)"

**Comment by Akuli** [comment]
Parsing `Content-Type` would also be pretty straight-forward with a regex. [Its format is not very complicated](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html).
