### ISSUE TITLE
can't publish on pypi

### ISSUE THREAD

**Issue by Akuli** [PurpleMyst/sansio-lsp-client#61]
CI publish job fails with error `400 User 'PurpleMyst' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.`

Then I tried creating my own pypi api token and just running the publishing command locally. I got `403 The user 'Akuli' isn't allowed to upload to project 'sansio-lsp-client'.`

@PurpleMyst please help

**Comment by Akuli** [comment]
I might publish `sansio-lsp-client-2` if I don't hear back from PurpleMyst during the next few weeks. I hope he's still alive, we were pretty close online friends when we were both learning to program...

**Comment by PurpleMyst** [comment]
I'm alive! I just got done with my bachelor degree in cybernetic engineering, so I have the summer free now.

**Comment by PurpleMyst** [comment]
I've just verified my email address on pypi, so this should be fixed. Feel free to close once we're able to verify that I've done all that needs to be done.

**Comment by Moosems** [comment]
Congrats on the degree!!

**Comment by Akuli** [comment]
I see that this project was released 2 days ago. Let's reopen or make a new issue if we run into more problems.
